version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - '5306:3306'
    environment:
      - MYSQL_DB=learn
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_INITDB_ARGS=--encoding=UTF-8
